//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.13 at 10:16:55 AM EDT 
//


package com.bayer.validation.structure;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bayer.validation.structure package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ValidationCollection_QNAME = new QName("http://www.xframium.org/structureValidation", "validationCollection");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bayer.validation.structure
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ValidationCollection }
     * 
     */
    public ValidationCollection createValidationCollection() {
        return new ValidationCollection();
    }

    /**
     * Create an instance of {@link Validation }
     * 
     */
    public Validation createValidation() {
        return new Validation();
    }

    /**
     * Create an instance of {@link Attribute }
     * 
     */
    public Attribute createAttribute() {
        return new Attribute();
    }

    /**
     * Create an instance of {@link Tag }
     * 
     */
    public Tag createTag() {
        return new Tag();
    }

    /**
     * Create an instance of {@link TextContent }
     * 
     */
    public TextContent createTextContent() {
        return new TextContent();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidationCollection }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xframium.org/structureValidation", name = "validationCollection")
    public JAXBElement<ValidationCollection> createValidationCollection(ValidationCollection value) {
        return new JAXBElement<ValidationCollection>(_ValidationCollection_QNAME, ValidationCollection.class, null, value);
    }

}
